repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
# Lint: Dockerfile
- repo: https://github.com/hadolint/hadolint.git
  rev: v2.8.0
  hooks:
    - id: hadolint-docker
      entry: hadolint/hadolint:v2.8.0 hadolint
      args: ["--ignore=DL3008", "--ignore=DL3013", "--ignore=DL3018"]
# # Lint: YAML
# - repo: https://github.com/adrienverge/yamllint.git
#   rev: v1.26.3
#   hooks:
#     - id: yamllint
#       args:
# 	[
# 	  "-d {extends: relaxed, rules: {line-length: disable}, ignore: chart}",
# 	  "-s",
# 	]
#       files: \.(yaml|yml)$
